apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: gitops-demo-service
spec:
  type: LoadBalancer
  selector:
    app: gitops-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
