apiVersion: v1  # Kubernetes API sürümü, Service kaynakları için v1 kullanılır
kind: Service  # Kaynak türü, burada Service
metadata:
  namespace: default  # Service’in hangi namespace’de oluşturulacağı
  name: gitops-demo-service  # Service’in ismi
spec:
  type: LoadBalancer  # Service türü, LoadBalancer bulutta bir dış IP sağlar ve trafiği pod’lara yönlendirir
  selector:
    app: gitops-demo  # Hangi pod’lara trafik yönlendirilecek, Deployment’daki pod etiketleri ile eşleşir
  ports:
    - protocol: TCP  # Kullanılacak protokol (TCP)
      port: 80  # Service’in dinlediği port (dışarıdan gelen trafik bu porttan gelir)
      targetPort: 3000  # Pod içerisindeki container’ın dinlediği port
